baseURL = 'https://www.amitsharma.tech/'
locale = 'en-gb'
title = 'Amit Sharma - Digital Product Leader'

    disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "Product leader with 18+ years of experience building fintech and SaaS products. Fractional CPO, startup mentor, educator, and builder."

[params.analytics]
  gtm = "GTM-PZLNJQ45"